package com.suong.entity;
// Generated Jun 20, 2017 8:30:48 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Giaovien generated by hbm2java
 */
@Entity
@Proxy(lazy= false)
@Table(name = "giaovien", catalog = "preschool")
public class Giaovien implements java.io.Serializable {

	private Integer id;
	private String teacherId;
	private String teacherName;
	private Date birthday;
	private String trinhdo;
	private String chuyenmon;
	private String address;
	private String phone;
	private Set<Iclass> iclasses = new HashSet<Iclass>(0);

	public Giaovien() {
	}

	public Giaovien(String teacherId, String teacherName, Date birthday, String trinhdo, String chuyenmon,
			String address, String phone) {
		this.teacherId = teacherId;
		this.teacherName = teacherName;
		this.birthday = birthday;
		this.trinhdo = trinhdo;
		this.chuyenmon = chuyenmon;
		this.address = address;
		this.phone = phone;
	}

	public Giaovien(String teacherId, String teacherName, Date birthday, String trinhdo, String chuyenmon,
			String address, String phone, Set<Iclass> iclasses) {
		this.teacherId = teacherId;
		this.teacherName = teacherName;
		this.birthday = birthday;
		this.trinhdo = trinhdo;
		this.chuyenmon = chuyenmon;
		this.address = address;
		this.phone = phone;
		this.iclasses = iclasses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "teacher_id", nullable = false, length = 30)
	public String getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "teacher_name", nullable = false, length = 50)
	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Birthday", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "trinhdo", nullable = false, length = 50)
	public String getTrinhdo() {
		return this.trinhdo;
	}

	public void setTrinhdo(String trinhdo) {
		this.trinhdo = trinhdo;
	}

	@Column(name = "chuyenmon", nullable = false, length = 30)
	public String getChuyenmon() {
		return this.chuyenmon;
	}

	public void setChuyenmon(String chuyenmon) {
		this.chuyenmon = chuyenmon;
	}

	@Column(name = "Address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<Iclass> getIclasses() {
		return this.iclasses;
	}

	public void setIclasses(Set<Iclass> iclasses) {
		this.iclasses = iclasses;
	}

}
