package com.suong.entity;
// Generated Jun 18, 2017 4:58:24 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hocsinh generated by hbm2java
 */
@Entity
@Table(name = "hocsinh", catalog = "preschool")
public class Hocsinh implements java.io.Serializable {

	private Integer id;
	private String studentId;
	private String studentName;
	private Date ngaysinh;
	private Boolean gioitinh;
	private String diachi;
	private Date ngayvaotruong;
	private String tinhtrangsuckhoe;
	private Set<Phanlop> phanlops = new HashSet<Phanlop>(0);
	private Set<Nkdkh> nkdkhs = new HashSet<Nkdkh>(0);
	private Set<Nktheodoi> nktheodois = new HashSet<Nktheodoi>(0);
	private Set<Khamsuckhoe> khamsuckhoes = new HashSet<Khamsuckhoe>(0);
	private Set<Thutienhoc> thutienhocs = new HashSet<Thutienhoc>(0);

	public Hocsinh() {
	}

	public Hocsinh(String studentId, String studentName) {
		this.studentId = studentId;
		this.studentName = studentName;
	}

	public Hocsinh(String studentId, String studentName, Date ngaysinh, Boolean gioitinh, String diachi,
			Date ngayvaotruong, String tinhtrangsuckhoe, Set<Phanlop> phanlops, Set<Nkdkh> nkdkhs,
			Set<Nktheodoi> nktheodois, Set<Khamsuckhoe> khamsuckhoes, Set<Thutienhoc> thutienhocs) {
		this.studentId = studentId;
		this.studentName = studentName;
		this.ngaysinh = ngaysinh;
		this.gioitinh = gioitinh;
		this.diachi = diachi;
		this.ngayvaotruong = ngayvaotruong;
		this.tinhtrangsuckhoe = tinhtrangsuckhoe;
		this.phanlops = phanlops;
		this.nkdkhs = nkdkhs;
		this.nktheodois = nktheodois;
		this.khamsuckhoes = khamsuckhoes;
		this.thutienhocs = thutienhocs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "student_id", nullable = false, length = 30)
	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	@Column(name = "student_name", nullable = false, length = 50)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaysinh", length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "gioitinh")
	public Boolean getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(Boolean gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Column(name = "diachi", length = 100)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngayvaotruong", length = 10)
	public Date getNgayvaotruong() {
		return this.ngayvaotruong;
	}

	public void setNgayvaotruong(Date ngayvaotruong) {
		this.ngayvaotruong = ngayvaotruong;
	}

	@Column(name = "tinhtrangsuckhoe", length = 30)
	public String getTinhtrangsuckhoe() {
		return this.tinhtrangsuckhoe;
	}

	public void setTinhtrangsuckhoe(String tinhtrangsuckhoe) {
		this.tinhtrangsuckhoe = tinhtrangsuckhoe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Phanlop> getPhanlops() {
		return this.phanlops;
	}

	public void setPhanlops(Set<Phanlop> phanlops) {
		this.phanlops = phanlops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Nkdkh> getNkdkhs() {
		return this.nkdkhs;
	}

	public void setNkdkhs(Set<Nkdkh> nkdkhs) {
		this.nkdkhs = nkdkhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Nktheodoi> getNktheodois() {
		return this.nktheodois;
	}

	public void setNktheodois(Set<Nktheodoi> nktheodois) {
		this.nktheodois = nktheodois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Khamsuckhoe> getKhamsuckhoes() {
		return this.khamsuckhoes;
	}

	public void setKhamsuckhoes(Set<Khamsuckhoe> khamsuckhoes) {
		this.khamsuckhoes = khamsuckhoes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Thutienhoc> getThutienhocs() {
		return this.thutienhocs;
	}

	public void setThutienhocs(Set<Thutienhoc> thutienhocs) {
		this.thutienhocs = thutienhocs;
	}

}
