package com.suong.entity;
// Generated Jun 20, 2017 8:30:48 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Iclass generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "iclass", catalog = "preschool", uniqueConstraints = @UniqueConstraint(columnNames = "malop"))
public class Iclass implements java.io.Serializable {

	private Integer id;
	private Giaovien giaovien;
	private String malop;
	private String tenlop;
	private String namhoc;
	private int quantity;
	private Set<Hocsinh> hocsinhs = new HashSet<Hocsinh>(0);

	public Iclass() {
	}

	public Iclass(Giaovien giaovien, String malop, String tenlop, String namhoc, int quantity) {
		this.giaovien = giaovien;
		this.malop = malop;
		this.tenlop = tenlop;
		this.namhoc = namhoc;
		this.quantity = quantity;
	}

	public Iclass(Giaovien giaovien, String malop, String tenlop, String namhoc, int quantity, Set<Hocsinh> hocsinhs) {
		this.giaovien = giaovien;
		this.malop = malop;
		this.tenlop = tenlop;
		this.namhoc = namhoc;
		this.quantity = quantity;
		this.hocsinhs = hocsinhs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "magv", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@Column(name = "malop", unique = true, nullable = false, length = 50)
	public String getMalop() {
		return this.malop;
	}

	public void setMalop(String malop) {
		this.malop = malop;
	}

	@Column(name = "tenlop", nullable = false, length = 100)
	public String getTenlop() {
		return this.tenlop;
	}

	public void setTenlop(String tenlop) {
		this.tenlop = tenlop;
	}

	@Column(name = "namhoc", nullable = false, length = 50)
	public String getNamhoc() {
		return this.namhoc;
	}

	public void setNamhoc(String namhoc) {
		this.namhoc = namhoc;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iclass")
	public Set<Hocsinh> getHocsinhs() {
		return this.hocsinhs;
	}

	public void setHocsinhs(Set<Hocsinh> hocsinhs) {
		this.hocsinhs = hocsinhs;
	}

}
