package com.suong.entity;
// Generated Jun 18, 2017 4:58:24 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nkdkh generated by hbm2java
 */
@Entity
@Table(name = "nkdkh", catalog = "preschool")
public class Nkdkh implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private Hocsinh hocsinh;
	private Phuhuynh phuhuynh;
	private String sodon;
	private String loptuoi;
	private Date ngaydangki;

	public Nkdkh() {
	}

	public Nkdkh(Employee employee, Hocsinh hocsinh, Phuhuynh phuhuynh, String sodon, String loptuoi, Date ngaydangki) {
		this.employee = employee;
		this.hocsinh = hocsinh;
		this.phuhuynh = phuhuynh;
		this.sodon = sodon;
		this.loptuoi = loptuoi;
		this.ngaydangki = ngaydangki;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nhanvien", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hocsinh", nullable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "phuhuynh", nullable = false)
	public Phuhuynh getPhuhuynh() {
		return this.phuhuynh;
	}

	public void setPhuhuynh(Phuhuynh phuhuynh) {
		this.phuhuynh = phuhuynh;
	}

	@Column(name = "sodon", nullable = false, length = 10)
	public String getSodon() {
		return this.sodon;
	}

	public void setSodon(String sodon) {
		this.sodon = sodon;
	}

	@Column(name = "loptuoi", nullable = false, length = 10)
	public String getLoptuoi() {
		return this.loptuoi;
	}

	public void setLoptuoi(String loptuoi) {
		this.loptuoi = loptuoi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaydangki", nullable = false, length = 10)
	public Date getNgaydangki() {
		return this.ngaydangki;
	}

	public void setNgaydangki(Date ngaydangki) {
		this.ngaydangki = ngaydangki;
	}

}
