package com.suong.entity;
// Generated Jun 18, 2017 4:58:24 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nktheodoi generated by hbm2java
 */
@Entity
@Table(name = "nktheodoi", catalog = "preschool")
public class Nktheodoi implements java.io.Serializable {

	private Integer id;
	private Class1 class1;
	private Giaovien giaovien;
	private Hocsinh hocsinh;
	private Date ngaytheodoi;
	private boolean tinhtrang;
	private String bieuhiencuatre;

	public Nktheodoi() {
	}

	public Nktheodoi(Class1 class1, Giaovien giaovien, Hocsinh hocsinh, Date ngaytheodoi, boolean tinhtrang,
			String bieuhiencuatre) {
		this.class1 = class1;
		this.giaovien = giaovien;
		this.hocsinh = hocsinh;
		this.ngaytheodoi = ngaytheodoi;
		this.tinhtrang = tinhtrang;
		this.bieuhiencuatre = bieuhiencuatre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "malop", nullable = false)
	public Class1 getClass1() {
		return this.class1;
	}

	public void setClass1(Class1 class1) {
		this.class1 = class1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "magiaovien", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mahs", nullable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaytheodoi", nullable = false, length = 10)
	public Date getNgaytheodoi() {
		return this.ngaytheodoi;
	}

	public void setNgaytheodoi(Date ngaytheodoi) {
		this.ngaytheodoi = ngaytheodoi;
	}

	@Column(name = "tinhtrang", nullable = false)
	public boolean isTinhtrang() {
		return this.tinhtrang;
	}

	public void setTinhtrang(boolean tinhtrang) {
		this.tinhtrang = tinhtrang;
	}

	@Column(name = "bieuhiencuatre", nullable = false)
	public String getBieuhiencuatre() {
		return this.bieuhiencuatre;
	}

	public void setBieuhiencuatre(String bieuhiencuatre) {
		this.bieuhiencuatre = bieuhiencuatre;
	}

}
