package com.suong.entity;
// Generated Jun 25, 2017 10:47:14 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * Nktheodoi generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "nktheodoi", catalog = "preschool")
public class Nktheodoi implements java.io.Serializable {

	private Integer id;
	private Hocsinh hocsinh;
	private Date ngaytheodoi;
	private boolean tinhtrang;

	public Nktheodoi() {
	}

	public Nktheodoi(Hocsinh hocsinh, Date ngaytheodoi, boolean tinhtrang) {
		this.hocsinh = hocsinh;
		this.ngaytheodoi = ngaytheodoi;
		this.tinhtrang = tinhtrang;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mahs", nullable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaytheodoi", nullable = false, length = 10)
	public Date getNgaytheodoi() {
		return this.ngaytheodoi;
	}

	public void setNgaytheodoi(Date ngaytheodoi) {
		this.ngaytheodoi = ngaytheodoi;
	}

	@Column(name = "tinhtrang", nullable = false)
	public boolean isTinhtrang() {
		return this.tinhtrang;
	}

	public void setTinhtrang(boolean tinhtrang) {
		this.tinhtrang = tinhtrang;
	}

}
