package com.suong.entity;
// Generated Jun 18, 2017 4:58:24 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phanlop generated by hbm2java
 */
@Entity
@Table(name = "phanlop", catalog = "preschool")
public class Phanlop implements java.io.Serializable {

	private Integer id;
	private Class1 class1;
	private Hocsinh hocsinh;
	private String namhoc;

	public Phanlop() {
	}

	public Phanlop(Class1 class1, Hocsinh hocsinh) {
		this.class1 = class1;
		this.hocsinh = hocsinh;
	}

	public Phanlop(Class1 class1, Hocsinh hocsinh, String namhoc) {
		this.class1 = class1;
		this.hocsinh = hocsinh;
		this.namhoc = namhoc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "malop", nullable = false)
	public Class1 getClass1() {
		return this.class1;
	}

	public void setClass1(Class1 class1) {
		this.class1 = class1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mahocsinh", nullable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@Column(name = "namhoc", length = 100)
	public String getNamhoc() {
		return this.namhoc;
	}

	public void setNamhoc(String namhoc) {
		this.namhoc = namhoc;
	}

}
