package com.suong.entity;
// Generated Jun 18, 2017 4:58:24 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Phuhuynh generated by hbm2java
 */
@Entity
@Table(name = "phuhuynh", catalog = "preschool", uniqueConstraints = @UniqueConstraint(columnNames = "parent_id"))
public class Phuhuynh implements java.io.Serializable {

	private Integer id;
	private String parentId;
	private String parentName;
	private String namsinh;
	private String job;
	private String address;
	private String phone;
	private Set<Thutienhoc> thutienhocs = new HashSet<Thutienhoc>(0);
	private Set<Nkdkh> nkdkhs = new HashSet<Nkdkh>(0);

	public Phuhuynh() {
	}

	public Phuhuynh(String parentId, String parentName, String job, String address, String phone) {
		this.parentId = parentId;
		this.parentName = parentName;
		this.job = job;
		this.address = address;
		this.phone = phone;
	}

	public Phuhuynh(String parentId, String parentName, String namsinh, String job, String address, String phone,
			Set<Thutienhoc> thutienhocs, Set<Nkdkh> nkdkhs) {
		this.parentId = parentId;
		this.parentName = parentName;
		this.namsinh = namsinh;
		this.job = job;
		this.address = address;
		this.phone = phone;
		this.thutienhocs = thutienhocs;
		this.nkdkhs = nkdkhs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "parent_id", unique = true, nullable = false, length = 30)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "parent_name", nullable = false, length = 40)
	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	@Column(name = "namsinh", length = 100)
	public String getNamsinh() {
		return this.namsinh;
	}

	public void setNamsinh(String namsinh) {
		this.namsinh = namsinh;
	}

	@Column(name = "Job", nullable = false, length = 30)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "Address", nullable = false, length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phuhuynh")
	public Set<Thutienhoc> getThutienhocs() {
		return this.thutienhocs;
	}

	public void setThutienhocs(Set<Thutienhoc> thutienhocs) {
		this.thutienhocs = thutienhocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phuhuynh")
	public Set<Nkdkh> getNkdkhs() {
		return this.nkdkhs;
	}

	public void setNkdkhs(Set<Nkdkh> nkdkhs) {
		this.nkdkhs = nkdkhs;
	}

}
