package com.suong.entity;
// Generated Jun 28, 2017 11:53:33 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * Thutienhoc generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "thutienhoc", catalog = "preschool")
public class Thutienhoc implements java.io.Serializable {

	private Integer id;
	private Hocsinh hocsinh;
	private String mabienlai;
	private Date ngaythu;
	private Integer tienhocphi;
	private Float tienan;
	private Float tienphuthu;
	private Float tongtien;
	private String namhoc;
	private Integer tiendadong;
	private Integer tienchuadong;

	public Thutienhoc() {
	}

	public Thutienhoc(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	public Thutienhoc(Hocsinh hocsinh, String mabienlai, Date ngaythu, Integer tienhocphi, Float tienan,
			Float tienphuthu, Float tongtien, String namhoc, Integer tiendadong, Integer tienchuadong) {
		this.hocsinh = hocsinh;
		this.mabienlai = mabienlai;
		this.ngaythu = ngaythu;
		this.tienhocphi = tienhocphi;
		this.tienan = tienan;
		this.tienphuthu = tienphuthu;
		this.tongtien = tongtien;
		this.namhoc = namhoc;
		this.tiendadong = tiendadong;
		this.tienchuadong = tienchuadong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mahs", nullable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@Column(name = "mabienlai", length = 50)
	public String getMabienlai() {
		return this.mabienlai;
	}

	public void setMabienlai(String mabienlai) {
		this.mabienlai = mabienlai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaythu", length = 10)
	public Date getNgaythu() {
		return this.ngaythu;
	}

	public void setNgaythu(Date ngaythu) {
		this.ngaythu = ngaythu;
	}

	@Column(name = "tienhocphi")
	public Integer getTienhocphi() {
		return this.tienhocphi;
	}

	public void setTienhocphi(Integer tienhocphi) {
		this.tienhocphi = tienhocphi;
	}

	@Column(name = "tienan", precision = 12, scale = 0)
	public Float getTienan() {
		return this.tienan;
	}

	public void setTienan(Float tienan) {
		this.tienan = tienan;
	}

	@Column(name = "tienphuthu", precision = 12, scale = 0)
	public Float getTienphuthu() {
		return this.tienphuthu;
	}

	public void setTienphuthu(Float tienphuthu) {
		this.tienphuthu = tienphuthu;
	}

	@Column(name = "tongtien", precision = 12, scale = 0)
	public Float getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(Float tongtien) {
		this.tongtien = tongtien;
	}

	@Column(name = "namhoc", length = 50)
	public String getNamhoc() {
		return this.namhoc;
	}

	public void setNamhoc(String namhoc) {
		this.namhoc = namhoc;
	}

	@Column(name = "tiendadong")
	public Integer getTiendadong() {
		return this.tiendadong;
	}

	public void setTiendadong(Integer tiendadong) {
		this.tiendadong = tiendadong;
	}

	@Column(name = "tienchuadong")
	public Integer getTienchuadong() {
		return this.tienchuadong;
	}

	public void setTienchuadong(Integer tienchuadong) {
		this.tienchuadong = tienchuadong;
	}

}
