package com.suong.entity;
// Generated Jun 18, 2017 4:58:24 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thutienhoc generated by hbm2java
 */
@Entity
@Table(name = "thutienhoc", catalog = "preschool")
public class Thutienhoc implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private Hocsinh hocsinh;
	private Phuhuynh phuhuynh;
	private String sobienlai;
	private Date ngaythu;
	private int tienhocphi;
	private float tienan;
	private float tienphuthu;
	private float tongtien;

	public Thutienhoc() {
	}

	public Thutienhoc(Employee employee, Hocsinh hocsinh, Phuhuynh phuhuynh, String sobienlai, Date ngaythu,
			int tienhocphi, float tienan, float tienphuthu, float tongtien) {
		this.employee = employee;
		this.hocsinh = hocsinh;
		this.phuhuynh = phuhuynh;
		this.sobienlai = sobienlai;
		this.ngaythu = ngaythu;
		this.tienhocphi = tienhocphi;
		this.tienan = tienan;
		this.tienphuthu = tienphuthu;
		this.tongtien = tongtien;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manv", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mahs", nullable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maph", nullable = false)
	public Phuhuynh getPhuhuynh() {
		return this.phuhuynh;
	}

	public void setPhuhuynh(Phuhuynh phuhuynh) {
		this.phuhuynh = phuhuynh;
	}

	@Column(name = "Sobienlai", nullable = false, length = 10)
	public String getSobienlai() {
		return this.sobienlai;
	}

	public void setSobienlai(String sobienlai) {
		this.sobienlai = sobienlai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaythu", nullable = false, length = 10)
	public Date getNgaythu() {
		return this.ngaythu;
	}

	public void setNgaythu(Date ngaythu) {
		this.ngaythu = ngaythu;
	}

	@Column(name = "tienhocphi", nullable = false)
	public int getTienhocphi() {
		return this.tienhocphi;
	}

	public void setTienhocphi(int tienhocphi) {
		this.tienhocphi = tienhocphi;
	}

	@Column(name = "tienan", nullable = false, precision = 12, scale = 0)
	public float getTienan() {
		return this.tienan;
	}

	public void setTienan(float tienan) {
		this.tienan = tienan;
	}

	@Column(name = "tienphuthu", nullable = false, precision = 12, scale = 0)
	public float getTienphuthu() {
		return this.tienphuthu;
	}

	public void setTienphuthu(float tienphuthu) {
		this.tienphuthu = tienphuthu;
	}

	@Column(name = "tongtien", nullable = false, precision = 12, scale = 0)
	public float getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(float tongtien) {
		this.tongtien = tongtien;
	}

}
