package com.demo.entity;
// Generated May 22, 2017 2:35:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Class1 generated by hbm2java
 */
@Entity
@Proxy(lazy =false)
@Table(name = "class1", catalog = "preschool")
public class Class1 implements java.io.Serializable {

	private Integer id;
	private String classId;
	private String className;
	private Date intakeYear;
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Diemdanh> diemdanhs = new HashSet<Diemdanh>(0);
	private Set<Lichhoc> lichhocs = new HashSet<Lichhoc>(0);

	public Class1() {
	}

	public Class1(String classId, String className, Date intakeYear) {
		this.classId = classId;
		this.className = className;
		this.intakeYear = intakeYear;
	}

	public Class1(String classId, String className, Date intakeYear, Set<Student> students, Set<Employee> employees,
			Set<Diemdanh> diemdanhs, Set<Lichhoc> lichhocs) {
		this.classId = classId;
		this.className = className;
		this.intakeYear = intakeYear;
		this.students = students;
		this.employees = employees;
		this.diemdanhs = diemdanhs;
		this.lichhocs = lichhocs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "class_id", nullable = false, length = 50)
	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	@Column(name = "class_name", nullable = false, length = 50)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "intake_year", nullable = false, length = 0)
	public Date getIntakeYear() {
		return this.intakeYear;
	}

	public void setIntakeYear(Date intakeYear) {
		this.intakeYear = intakeYear;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "class1")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "class1")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "class1")
	public Set<Diemdanh> getDiemdanhs() {
		return this.diemdanhs;
	}

	public void setDiemdanhs(Set<Diemdanh> diemdanhs) {
		this.diemdanhs = diemdanhs;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "class1")
	public Set<Lichhoc> getLichhocs() {
		return this.lichhocs;
	}

	public void setLichhocs(Set<Lichhoc> lichhocs) {
		this.lichhocs = lichhocs;
	}

}
