package com.demo.entity;
// Generated May 22, 2017 2:35:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Diemdanh generated by hbm2java
 */
@Entity
@Table(name = "diemdanh", catalog = "preschool")
public class Diemdanh implements java.io.Serializable {

	private Integer id;
	private Class1 class1;
	private Student student;
	private Date ngay;
	private byte status;
	private int quantity;

	public Diemdanh() {
	}

	public Diemdanh(Class1 class1, Student student, Date ngay, byte status, int quantity) {
		this.class1 = class1;
		this.student = student;
		this.ngay = ngay;
		this.status = status;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classId", nullable = false)
	public Class1 getClass1() {
		return this.class1;
	}

	public void setClass1(Class1 class1) {
		this.class1 = class1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentId", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay", nullable = false, length = 10)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
