package com.demo.entity;
// Generated May 22, 2017 2:35:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hososk generated by hbm2java
 */
@Entity
@Table(name = "hososk", catalog = "preschool")
public class Hososk implements java.io.Serializable {

	private Integer id;
	private Student student;
	private String maHs;
	private Date ngaylap;
	private byte status;
	private Date ngayKhamDk;
	private String result;

	public Hososk() {
	}

	public Hososk(Student student, String maHs, Date ngaylap, byte status, Date ngayKhamDk, String result) {
		this.student = student;
		this.maHs = maHs;
		this.ngaylap = ngaylap;
		this.status = status;
		this.ngayKhamDk = ngayKhamDk;
		this.result = result;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentId", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "ma_hs", nullable = false, length = 50)
	public String getMaHs() {
		return this.maHs;
	}

	public void setMaHs(String maHs) {
		this.maHs = maHs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaylap", nullable = false, length = 10)
	public Date getNgaylap() {
		return this.ngaylap;
	}

	public void setNgaylap(Date ngaylap) {
		this.ngaylap = ngaylap;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngayKhamDK", nullable = false, length = 10)
	public Date getNgayKhamDk() {
		return this.ngayKhamDk;
	}

	public void setNgayKhamDk(Date ngayKhamDk) {
		this.ngayKhamDk = ngayKhamDk;
	}

	@Column(name = "result", nullable = false, length = 65535)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
