package com.demo.entity;
// Generated May 22, 2017 2:35:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lichhoc generated by hbm2java
 */
@Entity
@Table(name = "lichhoc", catalog = "preschool")
public class Lichhoc implements java.io.Serializable {

	private int id;
	private Class1 class1;
	private String noiDungHoc;

	public Lichhoc() {
	}

	public Lichhoc(int id, Class1 class1, String noiDungHoc) {
		this.id = id;
		this.class1 = class1;
		this.noiDungHoc = noiDungHoc;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classId", nullable = false)
	public Class1 getClass1() {
		return this.class1;
	}

	public void setClass1(Class1 class1) {
		this.class1 = class1;
	}

	@Column(name = "noiDungHoc", nullable = false, length = 65535)
	public String getNoiDungHoc() {
		return this.noiDungHoc;
	}

	public void setNoiDungHoc(String noiDungHoc) {
		this.noiDungHoc = noiDungHoc;
	}

}
