package com.demo.entity;
// Generated May 22, 2017 2:35:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Thuchi generated by hbm2java
 */
@Entity
@Table(name = "thuchi", catalog = "preschool", uniqueConstraints = @UniqueConstraint(columnNames = "MaPT"))
public class Thuchi implements java.io.Serializable {

	private Integer id;
	private Student student;
	private String maPt;
	private int soTienThu;
	private String noiDungThu;
	private byte status;

	public Thuchi() {
	}

	public Thuchi(Student student, String maPt, int soTienThu, String noiDungThu, byte status) {
		this.student = student;
		this.maPt = maPt;
		this.soTienThu = soTienThu;
		this.noiDungThu = noiDungThu;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTre", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "MaPT", unique = true, nullable = false, length = 50)
	public String getMaPt() {
		return this.maPt;
	}

	public void setMaPt(String maPt) {
		this.maPt = maPt;
	}

	@Column(name = "soTienThu", nullable = false)
	public int getSoTienThu() {
		return this.soTienThu;
	}

	public void setSoTienThu(int soTienThu) {
		this.soTienThu = soTienThu;
	}

	@Column(name = "noiDungThu", nullable = false, length = 65535)
	public String getNoiDungThu() {
		return this.noiDungThu;
	}

	public void setNoiDungThu(String noiDungThu) {
		this.noiDungThu = noiDungThu;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
